version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: tap
    versions:
    - 14.11.0
    - 15.0.0
    - 15.0.1
    - 15.0.2
    - 15.0.3
    - 15.0.4
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: semantic-release
    versions:
    - 17.3.7
    - 17.3.8
    - 17.3.9
    - 17.4.0
    - 17.4.1
